class CategoryTerms:
    def __init__(self):
        self.terms = {
            # Ekonomi terimleri (60+ terim)
            'faiz': 1.3, 'dolar': 1.3, 'euro': 1.3, 'borsa': 1.3, 'hisse': 1.3,
            'ekonomi': 1.3, 'enflasyon': 1.3, 'bitcoin': 1.3, 'kripto': 1.3,
            'altin': 1.3, 'petrol': 1.3, 'merkez bankası': 1.3, 'banka': 1.3,
            'piyasa': 1.3, 'endeks': 1.3, 'fiyat': 1.3, 'kur': 1.3,
            'yatirim': 1.3, 'portfoy': 1.3, 'tahvil': 1.3, 'doviz': 1.3,
            'finans': 1.3, 'kredi': 1.3, 'borc': 1.3, 'rezerv': 1.3,
            'sermaye': 1.3, 'broker': 1.3, 'trader': 1.3, 'futures': 1.3,
            'forex': 1.3, 'hedge': 1.3, 'margin': 1.3, 'likidite': 1.3,
            'deflasyon': 1.3, 'stagflasyon': 1.3, 'resesyon': 1.3, 'gdp': 1.3,
            'ihracat': 1.3, 'ithalat': 1.3, 'ticaret': 1.3, 'vergiler': 1.3,
            'zam': 1.3, 'pahali': 1.3, 'ucuz': 1.3, 'cuzdan': 1.3, 'para': 1.3,
            'maas': 1.3, 'asgari ucret': 1.3, 'tl': 1.3, 'turk lirasi': 1.3,
            'ekonomik': 1.3, 'market': 1.3, 'fiyatlar': 1.3, 'pahalilik': 1.3,
            'zamlar': 1.3, 'bütçe': 1.3, 'açık': 1.3, 'denge': 1.3, 'cari': 1.3,
            'tüketim': 1.3, 'tasarruf': 1.3, 'yatırım fonu': 1.3, 'bono': 1.3,
            'swap': 1.3, 'arbitraj': 1.3, 'spekülasyon': 1.3, 'emtia': 1.3,
            'gayrimenkul': 1.3, 'ipotek': 1.3, 'kripto varlık': 1.3, 'coin': 1.3,
            'token': 1.3, 'stablecoin': 1.3, 'defter değeri': 1.3, 'piyasa değeri': 1.3,

            # Sağlık terimleri (80+ terim)
            'hastane': 1.5, 'doktor': 1.5, 'saglik': 1.5, 'virus': 1.4, 'asi': 1.4,
            'hastalik': 1.4, 'tedavi': 1.5, 'ilac': 1.4, 'ambulans': 1.3,
            'hekim': 1.5, 'hasta': 1.4, 'pandemi': 1.4, 'covid': 1.3, 'corona': 1.3,
            'klinik': 1.4, 'muayene': 1.5, 'teshis': 1.5, 'semptom': 1.4,
            'acil': 1.5, 'cerrahi': 1.5, 'ameliyat': 1.5, 'antibiyotik': 1.4,
            'enfeksiyon': 1.4, 'bagisiklik': 1.4, 'kanser': 1.5, 'diyabet': 1.4,
            'kalp': 1.4, 'damar': 1.4, 'tansiyon': 1.4, 'poliklinik': 1.4,
            'yogun bakim': 1.5, 'eczane': 1.4, 'saglik ocagi': 1.4,
            'rehabilitasyon': 1.4, 'fizik tedavi': 1.4, 'psikoloji': 1.4,
            'psikiyatri': 1.5, 'depresyon': 1.4, 'anksiyete': 1.4, 'alerji': 1.3,
            'astim': 1.4, 'grip': 1.3, 'ateş': 1.3, 'aşı': 1.4,
            'bağışıklık sistemi': 1.4, 'vitamin': 1.3, 'mineral': 1.3,
            'diyet': 1.3, 'beslenme': 1.3, 'obezite': 1.4, 'zayıflama': 1.3,
            'fizyoterapi': 1.4, 'terapi': 1.4, 'nöroloji': 1.5, 'radyoloji': 1.5,
            'laboratuvar': 1.4, 'test': 1.4, 'kan tahlili': 1.4, 'mr': 1.5,
            'tomografi': 1.5, 'ultrason': 1.5, 'röntgen': 1.5, 'ekg': 1.5,
            'check-up': 1.4, 'organ nakli': 1.5, 'diyaliz': 1.5, 'kemoterapi': 1.5,
            'radyoterapi': 1.5, 'aşılama': 1.4, 'sağlık sigortası': 1.4,
            'tıbbi': 1.5, 'medikal': 1.5, 'sağlık hizmeti': 1.5, 'sağlık personeli': 1.5,
            'hemşire': 1.5, 'ebe': 1.4, 'paramedik': 1.4, 'acil tıp': 1.5,
            'aile hekimi': 1.5, 'uzman doktor': 1.5, 'konsültasyon': 1.5,
            'reçete': 1.5, 'ilaç tedavisi': 1.5, 'yan etki': 1.4, 'dozaj': 1.4,
            'tıbbi cihaz': 1.4, 'sağlık teknolojisi': 1.4, 'genetik': 1.5,
            'biyoteknoloji': 1.5, 'klinik araştirma': 1.5, 'tıbbi araştirma': 1.5,
            'ağız ve diş sağlığı': 1.4, 'implant': 1.4, 'ortodonti': 1.4, 'pedodonti': 1.3,
            'diş eti hastalığı': 1.3, 'kanal tedavisi': 1.4, 'dolgu': 1.3, 'diş taşı': 1.3,
            'ağız kokusu': 1.3, 'çene cerrahisi': 1.5, 'endodonti': 1.4, 'diş hekimi asistanı': 1.3,

            'anne sağlığı': 1.4, 'doğum': 1.4, 'doğum öncesi bakım': 1.4, 'sezaryen': 1.4,
            'normal doğum': 1.4, 'kadın doğum uzmanı': 1.5, 'jinekoloji': 1.5, 'gebelik takibi': 1.4,
            'hamilelik testi': 1.3, 'rahim filmi': 1.4, 'doğum kontrol hapı': 1.4,

            'çocuk sağlığı': 1.4, 'pediatri': 1.5, 'aşı takvimi': 1.4, 'bebek aşısı': 1.4,
            'çocuk doktoru': 1.5, 'yenidoğan': 1.4, 'emzirme danışmanlığı': 1.3,
            'ağız sütü': 1.3, 'gelişim takibi': 1.3,

            'halk sağlığı': 1.4, 'epidemiyoloji': 1.5, 'filyasyon': 1.5, 'bulaşıcı hastalık': 1.4,
            'hijyen': 1.3, 'sterilizasyon': 1.4, 'dezenfektan': 1.3, 'el yıkama': 1.3,
            'maske': 1.3, 'sosyal mesafe': 1.3, 'karantina': 1.4, 'izolasyon': 1.4,
            'kamu sağlığı kampanyası': 1.3,

            'göz sağlığı': 1.4, 'gözlük': 1.3, 'lens': 1.3, 'göz muayenesi': 1.4,
            'oftalmoloji': 1.5, 'göz tansiyonu': 1.4, 'katarakt': 1.5, 'retina': 1.4,
            'göz doktoru': 1.5, 'kornea': 1.4,

            'kulak burun boğaz': 1.5, 'kulak çınlaması': 1.3, 'sinüzit': 1.4, 'kulak iltihabı': 1.3,
            'boğaz enfeksiyonu': 1.4, 'geniz eti': 1.3, 'bademcik': 1.3, 'ses telleri': 1.3,
            'odyometri': 1.4,

            'ortopedi': 1.5, 'kas iskelet sistemi': 1.4, 'bel fıtığı': 1.4, 'boyun fıtığı': 1.4,
            'dizlik': 1.3, 'ameliyat öncesi hazırlık': 1.3, 'ameliyat sonrası bakım': 1.3,

            'kanser türleri': 1.5, 'meme kanseri': 1.5, 'prostat kanseri': 1.5, 'akciğer kanseri': 1.5,
            'kolon kanseri': 1.5, 'lenfoma': 1.5, 'kanser taraması': 1.4, 'mamografi': 1.4,

            'besin takviyesi': 1.3, 'omega 3': 1.3, 'protein tozu': 1.3, 'sporcu beslenmesi': 1.3,

            'psikolojik danışman': 1.4, 'terapi seansı': 1.4, 'bilişsel davranışçı terapi': 1.5,
            'grup terapisi': 1.3, 'EMDR terapisi': 1.4, 'stres yönetimi': 1.3,
            'motivasyon eksikliği': 1.3, 'kendine zarar verme': 1.4, 'bağımlılık': 1.4,

            'alkol bağımlılığı': 1.4, 'sigara bırakma': 1.3, 'madde bağımlılığı': 1.5,
            'rehabilitasyon merkezi': 1.4, 'psikososyal destek': 1.4, 'toplum sağlığı merkezi': 1.4,

            'doku uyuşmazlığı': 1.5, 'kan grubu': 1.3, 'kan uyuşmazlığı': 1.4,
            'plazma': 1.3, 'antikor': 1.4, 'antijen': 1.4,

            'laboratuvar teknisyeni': 1.4, 'patoloji': 1.5, 'biyopsi': 1.5, 'sitoloji': 1.4,
            'hematoloji': 1.4, 'idrar tahlili': 1.3, 'balgam testi': 1.3, 'gaita testi': 1.3,

            'yara bakımı': 1.4, 'bası yarası': 1.3, 'enfekte yara': 1.4, 'dikiş atmak': 1.4,
            'pansuman': 1.4, 'bandaj': 1.3, 'ameliyat dikişi': 1.4,
            'brusella': 1.3, 'menenjit': 1.4, 'romatizma': 1.4, 'migren': 1.4,
            'epilepsi': 1.5, 'parkinson': 1.5, 'alzheimer': 1.5,
            'otizm': 1.4, 'down sendromu': 1.4, 'otizm spektrum bozukluğu': 1.4,
            'ms hastalığı': 1.5, 'uyku bozukluğu': 1.3, 'uykusuzluk': 1.3,
            'solunum cihazı': 1.4, 'ventilatör': 1.4, 'nefes maskesi': 1.3,
            'acil servis': 1.5, 'triyaj': 1.4, 'kan alma': 1.3,
            'serum': 1.3, 'iv enjeksiyon': 1.4, 'kan şekeri ölçümü': 1.4,
            'glukometre': 1.3, 'kan basıncı ölçümü': 1.4, 'nabız': 1.3,
            'EKG cihazı': 1.4, 'defibrilatör': 1.5, 'kalp pili': 1.5,
            'pacemaker': 1.5, 'anjiyo': 1.5, 'stent': 1.4,
            'bypass': 1.5, 'açık kalp ameliyatı': 1.5, 'karaciğer yetmezliği': 1.5,
            'böbrek yetmezliği': 1.5, 'karaciğer nakli': 1.5, 'böbrek nakli': 1.5,
            'aile sağlığı merkezi': 1.4, 'toplum ruh sağlığı merkezi': 1.4,
            'psikiyatrist': 1.5, 'psikolog': 1.4, 'diyetisyen': 1.4,
            'beslenme uzmanı': 1.3, 'ağız sağlığı merkezi': 1.3,
            'diş hekimi': 1.4, 'protez': 1.3, 'kan bankası': 1.4,
            'kan bağışı': 1.4, 'organ bağışı': 1.5, 'ağrı kesici': 1.3,
            'kortizon': 1.4, 'antiviral': 1.4, 'antifungal': 1.4,
            'ilaç alerjisi': 1.4, 'doz aşımı': 1.4, 'reçeteli ilaç': 1.4,
            'raporlu ilaç': 1.3, 'evde sağlık hizmeti': 1.4, 'mobil sağlık birimi': 1.3,
            'yoğun bakım hemşiresi': 1.5, 'anestezi teknikeri': 1.4,
            'ameliyathane hemşiresi': 1.4, 'hasta hakları': 1.4,
            'bilgilendirilmiş onam': 1.5, 'tıbbi kayıt': 1.4, 'hasta dosyası': 1.4,
            'enfeksiyon hastalığı': 1.4, 'bağışıklık': 1.4, 'boğaz ağrısı': 1.3,
            'nefes darlığı': 1.4, 'baş ağrısı': 1.3, 'karın ağrısı': 1.3,
            'bulantı': 1.3, 'kusma': 1.3, 'ishal': 1.3, 'kabızlık': 1.3,
            'cilt hastalığı': 1.4, 'egzama': 1.3, 'sedef hastalığı': 1.3,
            'kanser tedavisi': 1.5, 'biyopsi': 1.4, 'immünoterapi': 1.5,
            'endoskopi': 1.5, 'kolonoskopi': 1.5, 'laparoskopi': 1.5,
            'narkoz': 1.4, 'anestezi': 1.5, 'lokal anestezi': 1.4,
            'genel anestezi': 1.5, 'ameliyathane': 1.4, 'operasyon': 1.4,
            'postoperatif': 1.4, 'preoperatif': 1.4, 'hijyen': 1.3,
            'sterilizasyon': 1.4, 'izolasyon': 1.4, 'karantina': 1.4,
            'aşı kartı': 1.3, 'sağlık taraması': 1.4, 'toplum sağlığı': 1.4,
            'sağlık eğitimi': 1.3, 'halk sağlığı': 1.4, 'epidemiyoloji': 1.5,
            'psikoterapi': 1.4, 'bilişsel terapi': 1.4, 'davranış terapisi': 1.4,
            'sağlık çalışanı': 1.5, 'yoğun bakım ünitesi': 1.5, 'hasta bakımı': 1.4,
            'tıbbi etik': 1.4, 'palyatif bakım': 1.5, 'hospis': 1.4,
            'yaşlı bakımı': 1.3, 'çocuk sağlığı': 1.4, 'ağız ve diş sağlığı': 1.4,
            'ortodonti': 1.4, 'diş tedavisi': 1.4, 'implant': 1.4,

            # Spor terimleri (80+ terim)
            'futbol': 1.3, 'basketbol': 1.3, 'sampiyonluk': 1.3, 'mac': 1.3,
            'gol': 1.3, 'transfer': 1.3, 'teknik': 1.3, 'direktor': 1.3,
            'takim': 1.3, 'lig': 1.3, 'sporcu': 1.3, 'antrenman': 1.3,
            'fenerbahce': 1.3, 'galatasaray': 1.3, 'besiktas': 1.3, 'trabzonspor': 1.3,
            'stadyum': 1.3, 'derbi': 1.3, 'kupa': 1.3, 'milli takim': 1.3,
            'voleybol': 1.3, 'tenis': 1.3, 'formula': 1.3, 'olimpiyat': 1.3,
            'sampiyonlar ligi': 1.3, 'avrupa ligi': 1.3, 'uefa': 1.3, 'fifa': 1.3,
            'atletizm': 1.3, 'maraton': 1.3, 'boks': 1.3, 'gures': 1.3,
            'antrenor': 1.3, 'hakem': 1.3, 'sari kart': 1.3, 'kirmizi kart': 1.3,
            'pole': 1.3, 'pozisyon': 1.3, 'yaris': 1.3, 'f1': 1.3, 'hamilton': 1.3,
            'verstappen': 1.3, 'euroleague': 1.3, 'basketbol takimi': 1.3,
            'galibiyet': 1.3, 'sut': 1.3, 'sayi': 1.3, 'puan': 1.3,
            'mac sonucu': 1.3, 'pas': 1.3, 'asist': 1.3, 'faul': 1.3,
            'penalti': 1.3, 'serbest vurus': 1.3, 'korner': 1.3, 'ofsayt': 1.3,
            'kaleci': 1.3, 'defans': 1.3, 'orta saha': 1.3, 'forvet': 1.3,
            'dribling': 1.3, 'top surme': 1.3, 'kaptan': 1.3, 'yedek kulubes': 1.3,
            'sezon': 1.3, 'devre': 1.3, 'uzatma': 1.3, 'penaltilar': 1.3,
            'turnuva': 1.3, 'gruplar': 1.3, 'elemeler': 1.3, 'play-off': 1.3,
            'karsilasma': 1.3, 'deplasman': 1.3, 'saha': 1.3, 'seyirci': 1.3,
            'taraftar': 1.3, 'tezahurat': 1.3, 'forma': 1.3, 'ayakkabi': 1.3,
            'sponsor': 1.3, 'reklam': 1.3, 'yayin': 1.3, 'canli': 1.3,
            'yorumcu': 1.3, 'analiz': 1.3, 'istatistik': 1.3, 'performans': 1.3,



            # Siyaset terimleri (100+ terim)
            'siyaset': 1.5, 'iktidar': 1.5, 'muhalefet': 1.5, 'tbmm': 1.5,
            'politika': 1.5, 'hukumet': 1.5, 'cumhurbaskani': 1.5, 'bakan': 1.5,
            'demokrasi': 1.5, 'anayasa': 1.5, 'kanun': 1.4, 'yasa': 1.4,
            'bakanlik': 1.4, 'diplomat': 1.4, 'buyukelci': 1.4, 'protokol': 1.3,
            'reform': 1.4, 'komisyon': 1.4, 'oylama': 1.5, 'veto': 1.5,
            'chp': 1.5, 'akp': 1.5, 'mhp': 1.5, 'iyi parti': 1.5,
            'deva': 1.5, 'gelecek': 1.5, 'zafer': 1.5, 'yeniden refah': 1.5,
            'genel baskan': 1.5, 'grup toplantisi': 1.4, 'miting': 1.5,
            'seçim': 1.5, 'sandık': 1.5, 'oy': 1.5, 'seçmen': 1.5, 'aday': 1.5,
            'kampanya': 1.5, 'propaganda': 1.4, 'afiş': 1.3, 'pankart': 1.3,
            'slogan': 1.3, 'kongre': 1.4, 'kurultay': 1.4, 'tüzük': 1.3,
            'parti programı': 1.4, 'manifesto': 1.4, 'koalisyon': 1.5,
            'ittifak': 1.5, 'cumhur': 1.5, 'millet': 1.5, 'siyasi kriz': 1.5,
            'dış politika': 1.5, 'iç politika': 1.5, 'ulusal': 1.4, 'yerel': 1.4,
            'meclis': 1.5, 'milletvekili': 1.5, 'bakan yardımcısı': 1.4,
            'genel sekreter': 1.4, 'parti sözcüsü': 1.5, 'siyasi danışman': 1.4,
            'seçim barajı': 1.5, 'seçim sistemi': 1.5, 'seçim güvenliği': 1.5,
            'siyasi parti': 1.5, 'siyasi hareket': 1.5, 'siyasi görüş': 1.5,
            'ideoloji': 1.5, 'sol': 1.5, 'sağ': 1.5, 'merkez': 1.5,
            'liberal': 1.4, 'muhafazakar': 1.4, 'milliyetçi': 1.4, 'sosyal demokrat': 1.4,
            'parlamenter sistem': 1.5, 'başkanlık sistemi': 1.5, 'yerel yönetim': 1.4,
            'belediye başkanı': 1.5, 'büyükşehir': 1.5, 'il başkanı': 1.4,
            'siyasi reform': 1.5, 'siyasi kriz': 1.5, 'siyasi gerilim': 1.5,
            'siyasi uzlaşı': 1.5, 'siyasi diyalog': 1.5, 'siyasi çözüm': 1.5,
            'meclis grubu': 1.4, 'parti grubu': 1.4, 'grup başkanvekili': 1.4,
            'parti teşkilatı': 1.4, 'siyasi faaliyet': 1.4, 'seçim çalışması': 1.5,
            'seçim vaadi': 1.5, 'seçim sonucu': 1.5, 'oy oranı': 1.5,
            'siyasi gündem': 1.5, 'güncel siyaset': 1.5, 'siyasi gelişme': 1.5,
            'siyasi tartışma': 1.5, 'siyasi polemik': 1.5, 'siyasi açıklama': 1.5,
            'parti politikası': 1.5, 'siyasi strateji': 1.5, 'siyasi taktik': 1.4,


            # Teknoloji terimleri (100+ terim)
            'teknoloji': 1.3, 'yazilim': 1.3, 'donanim': 1.3, 'telefon': 1.3,
            'bilgisayar': 1.3, 'internet': 1.3, 'uygulama': 1.3, 'yapay': 1.3,
            'zeka': 1.3, 'robot': 1.3, 'siber': 1.3, 'dijital': 1.3,
            'android': 1.3, 'ios': 1.3, 'apple': 1.3, 'samsung': 1.3,
            'microsoft': 1.3, 'google': 1.3, 'facebook': 1.3, 'twitter': 1.3,
            'instagram': 1.3, 'tiktok': 1.3, 'linkedin': 1.3, 'youtube': 1.3,
            'blockchain': 1.3, 'metaverse': 1.3, 'nft': 1.3, 'kripto para': 1.3,
            'bulut': 1.3, 'veri': 1.3, 'big data': 1.3, 'algoritma': 1.3,
            'programlama': 1.3, 'python': 1.3, 'java': 1.3, 'javascript': 1.3,
            'mobil': 1.3, 'tablet': 1.3, 'laptop': 1.3, 'masaustu': 1.3,
            '5g': 1.3, 'wifi': 1.3, 'bluetooth': 1.3, 'gps': 1.3,
            'yapay öğrenme': 1.3, 'makine öğrenmesi': 1.3, 'derin öğrenme': 1.3,
            'yapay sinir ağı': 1.3, 'veri madenciliği': 1.3, 'veri analizi': 1.3,
            'veri bilimi': 1.3, 'yapay görü': 1.3, 'nesne tanıma': 1.3,
            'sanal gerçeklik': 1.3, 'artırılmış gerçeklik': 1.3, 'vr': 1.3,
            'ar': 1.3, 'oyun': 1.3, 'oyun konsolu': 1.3, 'playstation': 1.3,
            'xbox': 1.3, 'nintendo': 1.3, 'steam': 1.3, 'epic games': 1.3,
            'geliştirici': 1.3, 'kod': 1.3, 'debug': 1.3, 'test': 1.3,
            'hata': 1.3, 'güncelleme': 1.3, 'yama': 1.3, 'sürüm': 1.3,
            'açık kaynak': 1.3, 'github': 1.3, 'gitlab': 1.3, 'bitbucket': 1.3,
            'framework': 1.3, 'kütüphane': 1.3, 'api': 1.3, 'rest api': 1.3,
            'microservice': 1.3, 'container': 1.3, 'docker': 1.3, 'kubernetes': 1.3,
            'devops': 1.3, 'ci/cd': 1.3, 'entegrasyon': 1.3, 'deploy': 1.3,
            'sunucu': 1.3, 'server': 1.3, 'cloud': 1.3, 'aws': 1.3,
            'azure': 1.3, 'google cloud': 1.3, 'hosting': 1.3, 'domain': 1.3,
            'ssl': 1.3, 'güvenlik': 1.3, 'şifreleme': 1.3, 'firewall': 1.3,
            'sızma testi': 1.3, 'etik hacker': 1.3, 'phishing': 1.3, 'malware': 1.3,
            'antivirüs': 1.3, 'backup': 1.3, 'kurtarma': 1.3, 'veri kaybı': 1.3,
            'donanım': 1.3, 'işlemci': 1.3, 'cpu': 1.3, 'gpu': 1.3,
            'ram': 1.3, 'ssd': 1.3, 'hard disk': 1.3, 'anakart': 1.3,
            'ekran kartı': 1.3, 'monitör': 1.3, 'klavye': 1.3, 'mouse': 1.3,
            'yazıcı': 1.3, 'tarayıcı': 1.3, 'ses sistemi': 1.3, 'kulaklık': 1.3
        }

    def get_terms(self):
        """Tüm kategori terimlerini ve ağırlıklarını döndürür."""
        return self.terms